### ISSUE TITLE
Collector script cannot find older storms' archive files

### ISSUE THREAD

**Issue by Matmorcat** [UNCG-CSE/Poststorm_Imagery#17]
Checklist of storms that have been accounted for in the `collector-expand` branch:

- [x] 14.  	Hurricane Sandy (2012)

- [x] 15.  	Hurricane Isaac (2012)

- [x] 16.  	Hurricane Irene (2011)

- [x] 17.  	Joplin, MO Tornado (2011)

- [x] 18.  	Tuscaloosa, AL Tornado (2011)

- [x] 19.  	North Dakota Flooding (2011)
                ***NOTE:** Website does not provide publicly available link to an archive,
                only individual images via a query to ArcGIS.*

- [x] 20.  	Hurricane Earl (2010)

- [x] 21.  	Nor'Easter Nov09 (2009)

- [x] 22.  	Hurricane Ike (2008)

- [x] 23.  	Hurricane Gustav (2008)

- [x] 24.  	Hurricane Humberto (2007)

- [x] 25.  	Tropical Storm Ernesto (2006)

- [x] 26.  	Hurricane Wilma (2005)

- [x] 27.  	Hurricane Rita (2005)

- [x] 28.  	Hurricane Ophelia (2005)

- [x] 29.  	Hurricane Katrina (2005)

- [x] 30.  	Hurricane Dennis (2005)
                ***NOTE:** Website does not provide any link to an archive,
                only individual images.*

- [x] 31.  	Hurricane Ivan (2004)
                ***NOTE:** Website does not provide any link to an archive,
                only individual images.*

- [x] 32.  	Hurricane Jeanne (2004)
                ***NOTE:** Website does not provide any link to an archive,
                only individual images.*

- [x] 33.  	Hurricane Isabel (2003)
                ***NOTE:** Website does not provide any link to an archive,
                only individual images.*

Additional changes to be implemented after:

- [x] Update documentation
- [x] Update unit tests

**Comment by ebgoldstein** [comment]
May I suggest a list (in the docs) of which storms will work and which are pending?

**Comment by Matmorcat** [comment]
Sounds like a good idea. I'll work on it today

**Comment by Matmorcat** [comment]
Added list to collector script documentation

![image](https://user-images.githubusercontent.com/3231137/65489288-d5727280-de78-11e9-996c-eaa7d89af7ba.png)

**Comment by Matmorcat** [comment]
Fixed
