### ISSUE TITLE
Create compressed versions of large JPEG files

### ISSUE THREAD

**Issue by Matmorcat** [UNCG-CSE/Poststorm_Imagery#19]
One of the things we need in order to serve images to users is a smaller, more compressed version of images that is <1 MB so that images on the web-page load quickly

- [x] Make a script to recursively resizes and compresses all JPEG files in the data directory (doesn't have to access .tar files, just the unzipped contents
- [x] Encapsulate methods in a class with methods that can be called by a runner / main method / command-line so that it can be integrated into the complete project. (Doesn't have to be object oriented)
- [x] Store all compressed / resized images in a new directory (e.g. `data/small/Florence`) with similar or the same name as the originals for easy accessing
- [x] All images are of decent quality, but favoring smaller file size for load times
- [x] All images are the same resolution (e.g. 1280 x 720 pixels)
- [x] All images preserve the originals' aspect ratios (e.g. if it's 16:9, resized ones should be 16:9)

**Comment by rintychy** [comment]
I will do that part

**Comment by Matmorcat** [comment]
You want to close the issue when you complete everything associated with it

**Comment by Matmorcat** [comment]
Don't close it until the task is complete in it's entirety, I think you keep accidentally closing it :P

**Comment by Matmorcat** [comment]
Completed
