### ISSUE TITLE
UI classification

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-CSE/Poststorm_Imagery#21]
@ShahNafisRafique : you asked for the buttons on the UI... So far I can think of 4 buttons in 2 categories... I'll add more here when I think of them...

### Setting:
- [x] Developed vs Undevelped (i.e., are there buildings in the image, user only select 1)
- [x] River, Marsh, Sandy Coastline (users should be able to select all 3)

### Storm Impact:
- [x] Visible Washover vs No Washover. (user only select 1)
- [x] Swash, Collision, Overwash, Inundation. (user only select 1)

There should be a 'Skip' Button

*added by Shah*

- [x] Textbox
- [x] Quick submit

**Comment by ShahNafisRafique** [comment]
I need to add a text box, and a quick skip for use cases like when the image is all water. Additionally I need to have the data from these radio/checkboxes stored into a database as right now they just get passed back to the server and nothing happens with them.

**Comment by ebgoldstein** [comment]
@ShahNafisRafique: skip button is for cases when user is confused or lazy or annoyed...
- [ ] Text box should be called 'notes'
- [ ] I would add a 'water only' option in under the 'Setting' selection:
i.e., River, Marsh, Sandy Coastline, **Water Only**'

**Comment by Matmorcat** [comment]
Here are the code snippets for accessing the back-end API and an explanation of what they do. Not sure how the **water only** option is implemented on the front-end, so I left that surrounded by `???>` and `<???`

```javascript
    // Get the user's next image (when they press Skip, after tags are saved)
        args: [
            'tag', 'skip',
            `-p`, fullSizeImagePath,
            `-s`, smallSizeImagePath,
            `-u`, userId
        ]

    // Get the user's next image (when they click Submit, after tags are saved)
        args: [
            'tag', 'next',
            `-p`, fullSizeImagePath,
            `-s`, smallSizeImagePath,
            `-u`, userId
        ]

    // Submit a multiple choice response with only 1 possibility (they selected one of the choices)
    // - In cases where multiple choices cannot be selected at the same time, the options should
    //   be incremented from 0 (0 = first option, 1 = second, 2 = third) such that only one can
    //   be set at a time.
    // - This will update any existing value with the new one passed as optionChoice (type: int)
        args: [
            'tag', 'add',
            `-p`, fullSizeImagePath,
            `-s`, smallSizeImagePath,
            `-u`, userId,
            `-t`, tagID,         // The tag id (e.g. 'development')
            `-c`, tagContent     // The choice as an integer to set the tag to (e.g. 0 = undeveloped, 1 = developed)
        ]

    // tagID = 'development':
    // - tagContent: '0' = undeveloped, '1' = developed
    //
    // tagID = 'wash-over':
    // - tagContent: '0' = no wash-over, '1' = visible wash-over
    //
    // tagID = 'storm_impact':
    // - tagContent: '0' = swash, '1' = collision, '2' = over-wash, '3' = inundation

    // Submit a TRUE / FALSE value tag as TRUE (they CHECK a checkbox or one sub-option of a multiple selections option)
    // - Multiple choice selections should each be considered their own true / false tag
    // - Choices where there is multiple options, but the user can only choose one should NOT be handled
    //   as separate tags, though!
        args: [
            'tag', 'add',
            `-p`, fullSizeImagePath,
            `-s`, smallSizeImagePath,
            `-u`, userId,
            `-t`, tagID
        ]

    // Possible tagIDs = 'terrain_river', 'terrain_marsh', 'terrain_sandy_coastline', ???> 'terrain_water_only' <???

    // Submit additional text-based response (user has typed something in the 'Additional Notes' section)
        args: [
            'tag_notes',
            `-p`, fullSizeImagePath,
            `-s`, smallSizeImagePath,
            `-u`, userId,
            `-c`, comment  // The notes the user left for the current image (e.g. 'Wowe')
        ]
    // Comment: A string of any length (preferably enforce some length limit on front-end)
```

I'm thinking it might need a batch system, because as it stands, it will save to disk after every tag added, even if they're all added at the same time, but that shouldn't change the front-end implementation for now.

**Comment by Matmorcat** [comment]
Since we're in the process of implementing the back-end code into the dashboard, I propose some of the following for @ShahNafisRafique:

- [ ] Completely implement back-end code
- [ ] Ensure form submission works
- [ ] Test on a small subset of images to ensure the entire system is ready for production

**Comment by ShahNafisRafique** [comment]
done
