### ISSUE TITLE
Team name and emoji

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-CSE/Poststorm_Imagery#72]
Unfortunately I am going to ask that you all change the team name (and the emoji in the readme).

This needs to be done before ask other colleagues to join in and tag images. (and before any possible submission to anyplace).

Also, I'm going to try to show off all of your great work to a bunch of colleagues next week in Duck, NC

sorry for this request, but i have already fielded a few questions from colleagues re: the name choice.

**Comment by Matmorcat** [comment]
Shah and I understand the emoji can cause issues with file formats, but what's the issue with the team name?

**Comment by ebgoldstein** [comment]
I'll email you more in a second..

**Comment by ebgoldstein** [comment]
and just to be clear, it is just the text (C-Sick) and emoji in the readme (which is 'outward facing') that i would suggest changing (to keep the focus on your serious work). I'm not gonna do the change because that's usurping your (collective) agency...

**Comment by Matmorcat** [comment]
Fixed by 1d9e748
