### ISSUE TITLE
Data catalog

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-CSE/Poststorm_Imagery#75]
I suggest that there is a dataframe that catalogs all the jpgs and tiffs from all the storms. The catalog would have:
- storm name
- tar file where it resides
- day collected
- lat and long (scraped from Jpeg or Tiff tag)

and possibly some other stuff. 

This would be useful for:
1) it can be used in the `collect` script to find specific images (users could specify a lat long radius froma  given point, and pull all historic images, which would help to examine if some sites suffer repeat impacts (we call these 'hotspots')
2) This can be used for statistical work on # of images, locations of images, etc...

Any script that builds the dataframe catalog should be able to be run for future storms, so maybe this is a function that a user can call to rebuild the catalog for a future storm. 

Who was working with the lat/long dataframe?  @rintychy and @dlfosterbot ?

**Comment by Matmorcat** [comment]
I've been working on this in the `stats` branch. Anyone else is welcome to contribute to that branch. All the sources are under `src/Python/Poststorm_imagery/stats`
