### ISSUE TITLE
Back-end structure for handling manual tagging of images

### ISSUE THREAD

**Issue by Matmorcat** [UNCG-CSE/Poststorm_Imagery#86]
- [x] Images are loaded via their references in the catalog.csv
- [x] Auto-generate resized versions of images on the fly if missing
- [x] Image paths for both full size and resized images are handled
- [x] Tags are tracked based on user ID provided via command-line in a light-weight NoSQL fashion
- [x] Command-line options to add, update, and remove tags in the user's name
- [x] API can respond with a JSON object containing important information
- [x] Functionality to get a user's current image to tag and related info such as tags
- [x] Ability to skip images and pull the next image from the queue
- [x] Parallelism and disk persistence of state using a JSON pickle
- [x] Functionality to move images that exceed a specific threshold of unique users skipping
- [x] Basic redundancy check to reduce erroneous tagging of data
- [x] Pooling of tagging operations to avoid loading and saving to disk once per each tag in succession

**Comment by ebgoldstein** [comment]
redundacy would be ideal. and this is a good workflow for achieving it. 

In the ideal world, this workflow would be in place before the classification build-out (either with any CNN or another tool). However, i am mindful that the goal is to get an end-to-end tool working this semester. So I propose that you all build this redundancy if you have time and interest — but not at the expense of spending time on the classifier step...

thoughts (@Matmorcat and others)?

**Comment by Matmorcat** [comment]
It should be fairly easy to implement in the back-end, the front-end (Shah's dashboard) won't have to take it into account, since it will simply readd it to the pending tagging queue. Now if all 3 tag it differently from each other, it'll either save it to a file for manual review or something else. Building a whole front end system for this unlikely case would be a bit overkill

**Comment by Matmorcat** [comment]
I've implemented the code as follows:

Every time a user finishes tagging an image, the program will add it back into the pending (to be tagged) queue until there is a simple majority (2 users vs 1 user, 3 users vs 2 users, etc.), then it will remove it from the queue and mark it as done as far as tagging goes.

Relevant commits: 8388483 and a245c85

**Comment by Matmorcat** [comment]
The assigning portion of the dashboard is complete. Interpreting and extracting the data from the assigner state object is a separate set of tasks, so I'll create a new issue and mark this one as resolved!
